// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {risk} from '../models';
import {storage} from '../models';

export function AddSchedulePath(arg1:string):Promise<void>;

export function AnalyzeFile(arg1:string):Promise<main.ScanResult>;

export function CancelScan():Promise<void>;

export function CancelScheduledScan():Promise<void>;

export function GenerateReport(arg1:risk.AuditReport):Promise<string>;

export function GetAuditHistory():Promise<Array<storage.AuditEntry>>;

export function GetScheduleConfig():Promise<storage.ScheduleConfig>;

export function GetStats():Promise<storage.ScheduleConfig>;

export function GetUsername():Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function RedactFile(arg1:string):Promise<string>;

export function RemoveSchedulePath(arg1:string):Promise<void>;

export function ScanDirectory(arg1:string):Promise<risk.AuditReport>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function TriggerScheduledScan():Promise<void>;

export function UpdateScheduleConfig(arg1:storage.ScheduleConfig):Promise<void>;

export function UpdateStats(arg1:number,arg2:number,arg3:number):Promise<void>;
