// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSchedulePath(arg1) {
  return window['go']['main']['App']['AddSchedulePath'](arg1);
}

export function AnalyzeFile(arg1) {
  return window['go']['main']['App']['AnalyzeFile'](arg1);
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CancelScheduledScan() {
  return window['go']['main']['App']['CancelScheduledScan']();
}

export function GenerateReport(arg1) {
  return window['go']['main']['App']['GenerateReport'](arg1);
}

export function GetAuditHistory() {
  return window['go']['main']['App']['GetAuditHistory']();
}

export function GetScheduleConfig() {
  return window['go']['main']['App']['GetScheduleConfig']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function RedactFile(arg1) {
  return window['go']['main']['App']['RedactFile'](arg1);
}

export function RemoveSchedulePath(arg1) {
  return window['go']['main']['App']['RemoveSchedulePath'](arg1);
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function TriggerScheduledScan() {
  return window['go']['main']['App']['TriggerScheduledScan']();
}

export function UpdateScheduleConfig(arg1) {
  return window['go']['main']['App']['UpdateScheduleConfig'](arg1);
}

export function UpdateStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStats'](arg1, arg2, arg3);
}
